language: node_js
mode_js:
  - '0.10.32'
before_install:
  - 'gem install compass'
before_script:
  - 'bower install'
script:
  - 'grunt build'
after_success:
  - 'curl -T "dist/" -u $FTP_USER:$FTP_PASS ftp://$FTP_SERVER/$FTP_PATH'
notifications:
  slack: informaticalibre:DNQlxng6rbBkDU4quSRObnnV
