language: node_js
mode_js:
  - '0.10.32'
before_install:
  - 'gem install compass'
before_script:
  - 'bower install'
script:
  - 'grunt build'
  - 'cd dist'
  - 'zip -r info-libre.zip .'
  - 'curl -v --upload-file info-libre.zip -u $FTP_USER:$FTP_PASS ftp://$FTP_SERVER/$FTP_PATH/info-libre.zip'
notifications:
  email: false
  slack: informaticalibre:DNQlxng6rbBkDU4quSRObnnV
