language: node_js
mode_js:
  - '0.10.32'
before_install:
  - 'gem install compass'
before_script:
  - 'bower install'
script:
  - 'grunt build'
  - 'cd dist'
  - 'zip -r info-libre.zip .'
  - 'curl --upload-file info-libre.zip -u $FTP_USER:$FTP_PASS ftp://$FTP_SERVER/$FTP_PATH/info-libre.zip'
  - 'curl -g http://$FTP_SERVER/$DEPLOY_SCRIPT_PATH/deploy.php -H "User-Agent:  Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:27.0) Gecko/20100101 Firefox/27.0"'
notifications:
  email: false
  slack: informaticalibre:DNQlxng6rbBkDU4quSRObnnV
